export const metadata = {
  title: "Didongviet.vn",
  description: "Generated by create next app",
};
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import NavFooter from "./components/header/NavFooter";
import Providers from "@/redux/Provider";
import global from "./global.css";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />

          {children}
          <Footer />
          <NavFooter />
        </Providers>
      </body>
    </html>
  );
}
